### ISSUE TITLE
some errors in v0.9.0

### ISSUE THREAD

**Issue by Haimana** [inspired-technologies/signalk-openweather-plugin#10]
Hello,

Running SK 2.8.1 on OP4/RPi5, openweather-plugin v0.9.0, even I have expected data, I get some errors:

![image](https://github.com/inspired-technologies/signalk-openweather-plugin/assets/60715651/b1c8d52a-a01b-44a5-901a-c8113e0b56bb)

`Jun 01 11:11:44 2024-06-01T08:11:44.216Z openweather-signalk Plugin stopping...
Jun 01 11:11:44 2024-06-01T08:11:44.217Z openweather-signalk Plugin stopped.
Jun 01 11:11:44 2024-06-01T08:11:44.218Z openweather-signalk Plugin starting ...
Jun 01 11:11:44 2024-06-01T08:11:44.219Z openweather-signalk Interval started, refresh rate 60min
Jun 01 11:11:44 error starting plugin: TypeError: Cannot read properties of undefined (reading 'split')
Jun 01 11:11:44 TypeError: Cannot read properties of undefined (reading 'split') at Object.preLoad (/home/pi/.signalk/node_modules/openweather-signalk/openweather.js:466:31) at plugin.start (/home/pi/.signalk/node_modules/openweather-signalk/index.js:48:23) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:305:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:490:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:171:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:477:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:149:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:119:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Function.handle (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:175:3) at router (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:328:13) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at ZIP (/usr/lib/node_modules/signalk-server/node_modules/express-easy-zip/index.js:133:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5)
Jun 01 11:11:44 POST /skServer/plugins/openweather-signalk/config 200 4.540 ms - 50
Jun 01 11:11:44 GET /skServer/plugins 304 10.613 ms - -
Jun 01 11:11:44 2024-06-01T08:11:44.273Z openweather-signalk OpenWeather Coordinates 43.808083333333336,28.58465
Jun 01 11:11:44 2024-06-01T08:11:44.317Z openweather-signalk Elevation set to -37.73m above sea level
Jun 01 11:11:44 2024-06-01T08:11:44.658Z openweather-signalk Forecast received for Sat Jun 01 2024 12:11:44 GMT+0300 (Eastern European Summer Time)
Jun 01 11:11:44 2024-06-01T08:11:44.661Z openweather-signalk { environment: { sunlight: { times: [Object] } }, pressure: 101942.96996573985, temperature: 297.02, relativeHumidity: 0.59, precipitation: { probability: 0 }, wind: { speed: 6.16, direction: 3.2288591161895095, gust: 7.1 }, weather: 'Clouds', description: 'broken clouds' }
Jun 01 11:11:44 ERROR: Write to InfluxDB failed. m [HttpError]: failure writing points to database: partial write: field type conflict: input field "value" on measurement "environment.forecast.pressure" is type float, already exists as type string dropped=2 at IncomingMessage.<anonymous> (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671) at IncomingMessage.emit (node:events:526:35) at endReadableNT (node:internal/streams/readable:1359:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { statusCode: 422, statusMessage: 'Unprocessable Entity', body: '{"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \\"value\\" on measurement \\"environment.forecast.pressure\\" is type float, already exists as type string dropped=2"}', contentType: 'application/json; charset=utf-8', json: { code: 'unprocessable entity', message: 'failure writing points to database: partial write: field type conflict: input field "value" on measurement "environment.forecast.pressure" is type float, already exists as type string dropped=2' }, code: 'unprocessable entity', _retryAfter: 0 }
Jun 01 11:11:44 ERROR: Write to InfluxDB failed. m [HttpError]: failure writing points to database: partial write: field type conflict: input field "value" on measurement "environment.forecast.weather.code" is type float, already exists as type string dropped=1 at IncomingMessage.<anonymous> (/home/pi/.signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671) at IncomingMessage.emit (node:events:526:35) at endReadableNT (node:internal/streams/readable:1359:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { statusCode: 422, statusMessage: 'Unprocessable Entity', body: '{"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \\"value\\" on measurement \\"environment.forecast.weather.code\\" is type float, already exists as type string dropped=1"}', contentType: 'application/json; charset=utf-8', json: { code: 'unprocessable entity', message: 'failure writing points to database: partial write: field type conflict: input field "value" on measurement "environment.forecast.weather.code" is type float, already exists as type string dropped=1' }, code: 'unprocessable entity', _retryAfter: 0 }`

I don't know if is related, but also freeboard-sk have an error (even is working properly)

![image](https://github.com/inspired-technologies/signalk-openweather-plugin/assets/60715651/589493b6-20d2-453b-902e-28372bf952b3)

Any advice will be appreciated, thank you

Fair wind,
Seb

**Comment by inspired-technologies** [comment]
Hi Seb, many thanks for raising this; the error shown is not impacting functionality of the plugin, yet fixed in Release 0.9.1. 
The freeboard-sk error as well as the InfluxDB type conflict should not be related to it - which plugin is used for the later?

**Comment by Haimana** [comment]
thank you for fast fix, I'll update it and report back ASAP
it seems the freeboard-sk error is not related, that error is coming also with signalk-openweather-plugin disabled.
just as info, freeboard-sk v2.8.1 abd signalk-to-influxdb2 v1.7.4

**Comment by Haimana** [comment]
yes, no more error in Dashboard / Plugin Status after updating to 0.9.1.
still have the InfluxDB error in Server Logs, visible (at least) when pressing the Submit button in plugin's config
